name       : faba-icon-theme-mono
version    : 4.3
release    : 4
source     :
    - git|https://github.com/snwh/faba-mono-icons.git : 2006c5281eb988c799068734f289a85443800cda
license    : GPL-3.0
summary    : Supplementary icons for the Faba icon theme
component  : desktop.theme
description: |
    Supplementary icons for the Faba icon theme
rundeps    :
    - faba-icon-theme
    - moka-icon-theme
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
