name       : faba-icon-theme-mono
version    : 4.3
release    : 2
source     :
    - https://solus-project.com/sources/Faba-Mono-4.3.tar.xz : f6cf1c391fd9824e77288ff9edd469f2c6f37809ea9fca71a42798b4810390a7
license    : GPL-3.0
summary    : Supplementary icons for the Faba icon theme
description: |
    Supplementary icons for the Faba icon theme
rundeps    :
    - faba-icon-theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
