name       : faba-icon-theme-mono
version    : 4.2
release    : 1
source     :
    - https://github.com/moka-project/faba-mono-icons/raw/master/faba-mono-icons-4.2.tar.gz : 88553758d1c6a09281b2c7b27541975f88407b54713b426a68cf59db7d568695
license    : GPL-3.0
summary    : Supplementary icons for the Faba icon theme
description: |
    Supplementary icons for the Faba icon theme
rundeps    :
    - faba-icon-theme
install: |
    mkdir -p $installdir/usr/share/icons
    cp -Rv Faba-Mono $installdir/usr/share/icons/.
    cp -Rv Faba-Mono-Dark $installdir/usr/share/icons/.
    chmod a+r -R $installdir/usr/share/icons
